export const headerConfig = [
  {
    id: 1,
    name: {
      am: "կինո",
      en: "Cinema",
      ru: "Кино",
    },
    genres: [
      {
        id: 1,
        am: "Սարսափ",
        en: "Horror",
        ru: "Ужасы",
        link: "/",
      },
      {
        id: 2,
        am: "Մանկական",
        en: "Kids movies",
        ru: "Детское",
        link: "/",
      },
      {
        id: 3,
        am: "Կատակերգություն",
        en: "Comedy",
        ru: "Комедия",
        link: "/",
      },
      {
        id: 4,
        am: "Բոլորը",
        en: "All",
        ru: "Все",
        link: "/",
      },
    ],
    link: "/",
  },
  {
    id: 2,
    name: {
      am: "Համերգ",
      en: "Concert",
      ru: "Концерты",
    },
    genres: [
      {
        id: 1,
        am: "Ռոք",
        en: "Rock",
        ru: "Рок",
        link: "/",
      },
      {
        id: 2,
        am: "Ջազ",
        en: "Jazz",
        ru: "Джаз",
        link: "/",
      },
      {
        id: 3,
        am: "Դասական",
        en: "Classical",
        ru: "Классика",
        link: "/",
      },
      {
        id: 4,
        am: "Պար",
        en: "Dance",
        ru: "Танцы",
        link: "/",
      },
      {
        id: 5,
        am: "Բոլորը",
        en: "All",
        ru: "Все",
        link: "/",
      },
    ],
    link: "/",
  },
  {
    id: 3,
    name: {
      am: "Թատրոն",
      en: "Theater",
      ru: "Театр",
    },
    genres: [
      {
        id: 1,
        am: "Տիկնիկային",
        en: "Puppetry",
        ru: "Кукольный",
        link: "/",
      },
      {
        id: 2,
        am: "Կատակերգություն",
        en: "Comedy",
        ru: "Комедия",
        link: "/",
      },
      {
        id: 3,
        am: "Stand-up",
        en: "Stand-up",
        ru: "Stand-up",
        link: "/",
      },
      {
        id: 4,
        am: "Մանկական",
        en: "For kids",
        ru: "Детский",
        link: "/",
      },
      {
        id: 5,
        am: "Բոլորը",
        en: "All",
        ru: "Все",
        link: "/",
      },
    ],
    link: "/",
  },
  {
    id: 4,
    name: {
      am: "Օպերա և բալետ",
      en: "Opera & Ballet",
      ru: "Опера и балет",
    },
    genres: [
      {
        id: 1,
        am: "Օպերա",
        en: "Opera",
        ru: "Опера",
        link: "/",
      },
      {
        id: 2,
        am: "Բալետ",
        en: "Ballet",
        ru: "Балет",
        link: "/",
      },
      {
        id: 3,
        am: "Օպերետ",
        en: "Operetta",
        ru: "Оперетта",
        link: "/",
      },
      {
        id: 4,
        am: "Բոլորը",
        en: "All",
        ru: "Все",
        link: "/",
      },
    ],
    link: "/",
  },
  {
    id: 5,
    name: {
      am: "Ակումբ և փաբ",
      en: "Clubs & pubs",
      ru: "Клубы и пабы",
    },
    genres: [
      {
        id: 1,
        am: "Ակումբ",
        en: "Clubs",
        ru: "Клубы",
        link: "/",
      },
      {
        id: 2,
        am: "Փաբ",
        en: "Pub",
        ru: "Пабы",
        link: "/",
      },
      {
        id: 3,
        am: "Party",
        en: "Party  ",
        ru: "Вечеринки",
        link: "/",
      },
      {
        id: 4,
        am: "Բոլորը",
        en: "All",
        ru: "Все",
        link: "/",
      },
    ],
    link: "/",
  },
  {
    id: 6,
    name: {
      am: "Այլ",
      en: "Other",
      ru: "Другое",
    },
    genres: [
      {
        id: 1,
        am: "Ցուցահանդես",
        en: "Exhibitions",
        ru: "Выставка",
        link: "/",
      },
      {
        id: 2,
        am: "Սպորտ",
        en: "Sport",
        ru: "Спорт",
        link: "/",
      },
      {
        id: 3,
        am: "Կրկես",
        en: "Circus",
        ru: "Цирк",
        link: "/",
      },
      {
        id: 4,
        am: "IT",
        en: "IT",
        ru: "IT-события",
        link: "/",
      },
      {
        id: 5,
        am: "Բոլորը",
        en: "All",
        ru: "Все",
        link: "/",
      },
    ],
    link: "/",
  },
];
